import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import ItemDetail from '../../components/pages/ItemDetail'
import axios from 'axios'
import { useRouter } from 'next/router'

export async function getServerSideProps(context) {
  const nftid = context.params.nftid;
  console.log('context')
  // const { nftid } = router.query
  
  const res = await fetch(`http://localhost:4000/api/nft_listing/` + nftid)
  const data = await res.json()
  const nft = data[0];
  if (!data) {
    return {
      notFound: true,
    }
  }
  
  return {
    props: { nft }, // will be passed to the page component as props
  }
}


export default function NftDetail(props) {
  console.log('props')
  console.log(props)
  const [nftListings, setNftListings] = useState([]);
  const router = useRouter()
  
  console.log('pid')
  // console.log(nftid)
  useEffect(() => {
    axios.get('http://localhost:4000/api/nft_listings').then(response => {
      setNftListings(response.data)
    })
    // Update the document title using the browser API
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ItemDetail nft={props.nft} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
