import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import ItemDetail from '../../components/pages/ItemDetail'
import axios from 'axios'
import { useRouter } from 'next/router'
import BiddyHeader from '../../components/menu/BiddyHeader';
import constants from '../../src/constants';

export async function getServerSideProps(context) {
  const nftid = context.params.nftid;
  console.log('context')
  // const { nftid } = router.query
  
  const res = await fetch(constants.API_URL + `/api/nft_listing/` + nftid)
  const data = await res.json()
  const nft = data[0];
  if (!data) {
    return {
      notFound: true,
    }
  }
  
  return {
    props: { nft }, // will be passed to the page component as props
  }
}


export default function NftDetail(props) {
  console.log('props')
  console.log(props)
  const [nftListings, setNftListings] = useState([]);
  const router = useRouter()
  
  console.log('pid')
  console.log(props.nft)
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <BiddyHeader />
      <ItemDetail nft={props.nft} />

    </div>
  )
}
