import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomePage from '../components/pages/home'
import axios from 'axios'
import BiddyHeader from '../components/menu/BiddyHeader';
import constants from '../../src/constants';

export default function Home() {
  const [nftListings, setNftListings] = useState([]);
  useEffect(() => {
    axios.get(constants.API_URL + '/api/nft_listings').then(response => {
      setNftListings(response.data)
    })
    // Update the document title using the browser API
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BiddyHeader />

      <HomePage nftListings={nftListings} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
